name: robotics-demo
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10  # required by drake
  - pytorch
  - tqdm
  - pip
  - setuptools==65.5.0  # https://github.com/openai/gym/issues/3176
  - click
  - jupyter
  - pip:
      - drake
      - meshcat
  - pinocchio
  - crocoddyl
  - numpy
  - pytest
  - scipy
  - pyface
